### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by leizy1008** [elecho1/MPANet#1]
Hi, it seems that the pretrained model links (MPANet and NIMA) are not available any more. Could you please update them ? Thanks !

**Comment by elecho1** [comment]
Thank you for pointing it out!
I updated the links to those models. [#318dd21](https://github.com/elecho1/MPANet/commit/318dd218ed3bb41df1f5f518a197893bed3fa13f)
I hope this will help.

**Comment by leizy1008** [comment]
> Thank you for pointing it out! I updated the links to those models. [#318dd21](https://github.com/elecho1/MPANet/commit/318dd218ed3bb41df1f5f518a197893bed3fa13f) I hope this will help.

Thanks !
